### ISSUE TITLE
i got some problem on the project

### ISSUE THREAD

**Issue by Irics** [scrapinghub/scrapyjs#5]
I am a newbie on scrapy,I put this project scrapyjs into practice.It generate problem like"raise error.ReactorAlreadyInstalledError("reactor already installed")
ReactorAlreadyInstalledError: reactor already installed" when I add "gtk2reactor.install()" on __init__.py.How to make sure scrapy use gtk2reactor on  twisted?

**Comment by kmike** [comment]
Hi @Irics,

GTK version is discontinued; it lives in a branch now (https://github.com/scrapinghub/scrapyjs/tree/gtk).
