### ISSUE TITLE
Middlware - Too many open files

### ISSUE THREAD

**Issue by pontagon24** [scrapinghub/scrapyjs#6]
I have been running in to many problems with this middleware, especially random freezing and performance issues. I solved some of the freezing problems by not using Mongodb in my pipeline. 

However now i encountered a big problem that keeps coming back: 
GliB - Too many open files. 

I know what the error means, what i dont know is why? It seems that this keeps happening at the gtk.main() loop. 

Best Regards
Pontus

**Comment by kmike** [comment]
Hey @pontagon24,

GTK version is discontinued; it lives in a branch now (https://github.com/scrapinghub/scrapyjs/tree/gtk).
